version: "3.8"

services:
  retailpulse:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/secrets/gcp-key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-key.json
    working_dir: /app
    command: tail -f /dev/null

  airflow:
    image: apache/airflow:2.8.1-python3.11
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-key.json
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./dbt_project:/opt/airflow/dbt_project
      - ./scripts:/opt/airflow/scripts
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/secrets/gcp-key.json:ro
    ports:
      - "8080:8080"
    command: standalone
